name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
# pygments: true
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions
  
  
