name: kvrk
domain: kvrk.no
project: Infrastruktur for Forskning - kvrk
markdown: : redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
timezone: GB
permalink: /blog/:year/:month/:day/:title
permalink: /diagnosis/:year/:month/:day/:title
permalink: /prescription/:year/:month/:day/:title
permalink: /procedure/:year/:month/:day/:title

# pygments: true
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions
